### ISSUE TITLE
100% CPU usage when running with >f faults

### ISSUE THREAD

**Issue by mystenmark** [MystenLabs/sui#1529]
If you start up a validator that can't connect to all its peers, it consumes all available CPU. I assume it is constantly retrying to connect.

If this is indeed the cause, we need to have some reconnect delay, possible very short initially with exponential backoff. (cc @bmwill)

@asonnino You can probably replicate this by running the validator locally with non-existant peers in network.conf.

Also, we need to have logging when connects are failing.

**Comment by asonnino** [comment]
for the narwhal/tusk codebase it should be fine (we tested it and benchmarked it under faults countless times). The validator should start reconnecting with backoff: https://github.com/MystenLabs/narwhal/blob/5075909cc79dc824b937c93fd91164ae74e76042/network/src/reliable_sender.rs#L165

**Comment by asonnino** [comment]
Logging is here: https://github.com/MystenLabs/narwhal/blob/5075909cc79dc824b937c93fd91164ae74e76042/network/src/reliable_sender.rs#L164

**Comment by gdanezis** [comment]
This should be fixed before we go to devnet, since this code runs right?

**Comment by asonnino** [comment]
Where is the issue exactly (narwhal, Sui or the interface)? I think there was a config issue with narwhal that has been fixed, so you still see issues?

**Comment by mystenmark** [comment]
To replicate:

         ./target/debug/validator --genesis-config-path $HOME/dev/devnet/docker/validator/genesis.conf --address <address from network.conf>

When I do this locally, I do get logging, which is helpful (I did not see any logs when it was running in docker), but validator still immediately pegs the CPU at 100%.

It seems likely this failure mode will still occur when the configuration is valid, if another validator goes down.

**Comment by asonnino** [comment]
thanks,  I’ll check that first thing on Monday

**Comment by asonnino** [comment]
I didn't manage to replicate. I tried to run a testbed locally with 4 nodes (out of which one node is crashed).

<img width="1512" alt="Screenshot 2022-04-25 at 09 58 55" src="https://user-images.githubusercontent.com/28302983/165104420-2f801e32-4b62-4fac-969d-baaa0fc64e3a.png">

**Comment by mystenmark** [comment]
I don't know if this can be replicated with `sui start` - i have only seen this when running the validator binary.

**Comment by asonnino** [comment]
How can I replicate it by running the a network of validators locally? Do we have a tutorial by any change?

**Comment by mystenmark** [comment]
Please checkout branch `mlogan-repro-issue-1529`, and run `./repro-1529.sh` in the root

**Comment by asonnino** [comment]
Is this starting a single validator, right?

**Comment by asonnino** [comment]
I checked the problem and it seems that the module using all the CPU is `primary::block_remover`. Looking at the git history it seems this module has been recently added by @akichidis. @akichidis  any idea what may cause this problem?

**Comment by akichidis** [comment]
> I checked the problem and it seems that the module using all the CPU is `primary::block_remover`. Looking at the git history it seems this module has been recently added by @akichidis. @akichidis any idea what may cause this problem?

Ah that's very weird . @asonnino what's the tool you used to figure this out? Interesting to see the results. The weird thing is that the `block_remover` at the moment should practically do nothing, as no-one is calling it (e.x sending any commands to remove blocks etc - do something).

**Comment by asonnino** [comment]
It is printing the following error line many times
```
2022-04-25T17:59:58.954218Z ERROR worker::worker: Failed to deserialize primary message: io error: unexpected end of file
```
I am still investigating because I didn't manage to pinpoint the cause of the problem yet

**Comment by akichidis** [comment]
> Failed to deserialize primary message

This is though seems to be printed by the worker node, right? This is not primary. So a message is sent to a worker and this is failed to be deserialised

**Comment by asonnino** [comment]
yes it is very hard to track the issues, it seems we have been copy-pasting files in different repos for instance
https://github.com/MystenLabs/sui/blob/main/sui/src/validator.rs
and
https://github.com/MystenLabs/sui/blob/main/sui/src/validator.rs

**Comment by asonnino** [comment]
> > Failed to deserialize primary message
> 
> This is though seems to be printed by the worker node, right? This is not primary. So a message is sent to a worker and this is failed to be deserialised

Sorry I meant this one:
```
2022-04-25T18:14:55.477126Z ERROR primary::block_remover: no pending delete request has been found for key []
```

**Comment by akichidis** [comment]
> > > Failed to deserialize primary message
> > 
> > 
> > This is though seems to be printed by the worker node, right? This is not primary. So a message is sent to a worker and this is failed to be deserialised
> 
> Sorry I meant this one:
> 
> ```
> 2022-04-25T18:14:55.477126Z ERROR primary::block_remover: no pending delete request has been found for key []
> ```

Ok, from the above data then it seems like the worker (for whatever reason) is constantly sending to the `primary` a message multiple `WorkerPrimaryMessage::DeletedBatches` with `empty` batch digests vector. Probably need more data to investigate/replicate this.

**Comment by asonnino** [comment]
It seems there are many problems causing this issues. There is a misconfiguration on the committee (maybe one of our docker scripts?) and Narwhal way trying to sync empty parents (Narwhal was not built to run with less than 2f+1 honest nodes). 

This PR should take care of half of the problem: https://github.com/MystenLabs/sui/pull/1582
And this PR should fix the other half: https://github.com/MystenLabs/narwhal/pull/158

**Comment by asonnino** [comment]
> > > > Failed to deserialize primary message
> > > 
> > > 
> > > This is though seems to be printed by the worker node, right? This is not primary. So a message is sent to a worker and this is failed to be deserialised
> > 
> > 
> > Sorry I meant this one:
> > ```
> > 2022-04-25T18:14:55.477126Z ERROR primary::block_remover: no pending delete request has been found for key []
> > ```
> 
> Ok, from the above data then it seems like the worker (for whatever reason) is constantly sending to the `primary` a message multiple `WorkerPrimaryMessage::DeletedBatches` with `empty` batch digests vector. Probably need more data to investigate/replicate this.

This is an issue but I don't think it is the core problem burning all our CPU (so maybe it can wait)

**Comment by asonnino** [comment]
Edit: PR #1582 still does not seem to fix the issue. The CPU consumption goes back to 100% after a while (a few minutes rather than imeditaly). The Narwhal Primary (neither the worker nor consensus) seem to be the problem.

**Comment by asonnino** [comment]
To clearly see the issue, we can use the following script from `./sui`:
```
#!/bin/bash -e

cargo build --bin validator
./target/debug/validator --genesis-config-path $HOME/dev/devnet/docker/validator/genesis.conf --validator-idx 0 &
```
We then observe the CPU spiking to 100%. If however we have a quorum of nodes (thus less than `f` faults) the problem disappear: we can observe it by modifying the script like this:
```
#!/bin/bash -e

cargo build --bin validator
./target/debug/validator --genesis-config-path $HOME/dev/devnet/docker/validator/genesis.conf --validator-idx 0 &
./target/debug/validator --genesis-config-path $HOME/dev/devnet/docker/validator/genesis.conf --validator-idx 1 &
./target/debug/validator --genesis-config-path $HOME/dev/devnet/docker/validator/genesis.conf --validator-idx 2 &
```
