### ISSUE TITLE
Can not call api for sponsor Enoki

### ISSUE THREAD

**Issue by tranvanhai0504** [MystenLabs/sui#20263]
I have this error when try to call a function with sponsor api in my project with Enoki. But it always throw to me the 'gas_station_error' ( image below). I check the example repo and it was error too ( [https://enoki-example-app.vercel.app/](url) )

![image](https://github.com/user-attachments/assets/0de8c508-d7c0-429c-a46c-0935f279b401)

**Comment by stefan-mysten** [comment]
There might have been an issue going around that time, but it seems to have been resolved. Could you confirm that it works for you now? Thanks @tranvanhai0504

**Comment by tranvanhai0504** [comment]
It still getting error for now. The error have appear in yesterday afternoon. Before that time it working fine. And I have to go to Enoki https api doc for checked and called the sponsor api, it throw me the 401 error although I pasted the correctly private API key

![386173520-1aad446a-1b18-4c5c-a5ba-a01efebe0b07](https://github.com/user-attachments/assets/f814bf4f-7bcc-495a-aeb3-b7e61da36162)

**Comment by Jordan-Mysten** [comment]
This issue has been resolved
