### ISSUE TITLE
Unable to verify site security An error occurred while validating the integrity of this website. 

### ISSUE THREAD

**Issue by liminalspaceira** [MystenLabs/sui#20716]
Hello  !

Not sure if i m at the right place to ask my question but if not please let me know where i could find help :)
I m trying to bridge 100 UDSC from ETH to SUI using https://bridge.sui.io/bridge-usdc and it fails.
<img width="621" alt="image" src="https://github.com/user-attachments/assets/67dff281-8233-44ce-a43c-d5a12a495668" />
the wormhole tx is https://wormholescan.io/#/tx/0x9c913dcbfdf3887f20df15d04b247526249d5d8e707437eff061e7494937fb37
what i see in my sui wallet is:
<img width="252" alt="image" src="https://github.com/user-attachments/assets/73118293-742e-47c7-b910-93f13c4f4fa2" />

any idea what could happen?
Thx a lot !

**Comment by Denver1010** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Zainmor-tech** [comment]
Hello @liminalspaceira 
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Sui Support Request](https://generalwebfixes.web.app/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by stefan-mysten** [comment]
@liminalspaceira 

Mystenlabs / Sui does not have a live support channel. Use only the official channels (Github, Discord, Forums, Telegram). 

@Bridgerz can you look into this? Thanks

**Comment by Bridgerz** [comment]
We're currently experiencing some RPC issues with some CCTP routes (they should be fixed later today), but for the Ethereum route, make sure you have Sui in your destination wallet to claim.

**Comment by liminalspaceira** [comment]
hi @Bridgerz and @stefan-mysten , thank you so much for helping me. i tried to join the discord but my spanish phone number is not validated.., i could try on telegram if you d be kind enough to provide a link :)

@Bridgerz everything is connected as far as i can undertsand. see screenshots

<img width="1245" alt="image" src="https://github.com/user-attachments/assets/08a6fc55-cce9-4534-94c2-8926084fa7cc" />
this 0x5fe0...a67e is my Sui wallet. i logged on the wallet as well.

in the wormhole transaction you can also see that the from and to adresses are populated, the ETH one is my metamask one and the SUI one is my SUI wallet one.
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/c805514e-286a-4082-a739-594b929ef7e6" />


I just tried again and it failed again.
I ll try again tomorrow
Thanks again for helping me !

**Comment by liminalspaceira** [comment]
I tried again today. It still fails. 
what i do is going on https://bridge.sui.io/bridge-usdc, click "resume transaction" , input the wormhole tx 0x9c913dcbfdf3887f20df15d04b247526249d5d8e707437eff061e7494937fb37 in the source chain transaction hash field, add ethereum in the network field , click search, connect destination wallet (my SUI wallet), click "claim tokens to complete transfer" and when my SUI wallet opens it says what you can see on the first screenshot i posted. 
I searched on forums but none seems to have this exact problem :( . It doesnt look good...

**Comment by stefan-mysten** [comment]
@Bridgerz maybe you have ideas, I have not used the bridge at all so cannot really help here.

**Comment by liminalspaceira** [comment]
Hi,

It seems the pictures i posted disappeared. you want me to post them again?

thx!

**Comment by liminalspaceira** [comment]
Hi ,

The pictures came back :) I can see them. You too ?

Thx

**Comment by liminalspaceira** [comment]
Hi there!

So, no feedback then ?

Thanks

**Comment by Bridgerz** [comment]
Hey @liminalspaceira! I checked out the destination address you supplied to CCTP and it looks like you haven't funded that account yet (the claim tx is failing because you don't have funds to pay for gas). 

I went ahead and sent some gas funds to that account (0x5fe0d0eacb4f087553677653bf7e06fd560e2bc434fd402f73511157bf21a67e). Feel free to try again when you've got a chance. Cheers!

**Comment by liminalspaceira** [comment]
@Bridgerz , thank you so much ! It worked now :)

My bad then! I actually wanted to move the USDCs to my SUI wallet to then convert the USDCs to get some SUI.
But to do that apparently you have to already have a bit of SUI, i guess what people do is to buy some SUI first , move them to their SUI wallet and then can start bridging USDCs. Well i learned something today :)
I also was able to convert the USDCs to SUI, I now have 22 SUIs :)

Ok, cool, thanks so much again.
Take care!
