### ISSUE TITLE
[Slush web] Cannot verify signature of signed personal messages

### ISSUE THREAD

**Issue by bruceeewong** [MystenLabs/sui#22032]
## Steps to Reproduce Issue

1. Using mystem dapp kit, connect to Slush web, sign personal message.
2. Use verifyPersonalMessageSignature (from @mysten/js/verify) to verify the signed result
3. Error returned by the graphql response.

## Expected Result

Signature should be able to verify. As signatures from Slush extension that uses ZK account could pass the same verification function.

## Actual Result

![Image](https://github.com/user-attachments/assets/4ef5f2a7-2447-4f0f-aa68-d3f927d038e2)

## System Information

* OS: doesn't matter
* Compiler: doesn't matter

**Comment by williamrobertson13** [comment]
Hey @bruceeewong! This is fixed in https://github.com/MystenLabs/ts-sdks/issues/273

**Comment by bruceeewong** [comment]
@williamrobertson13 Hi William, I am actually using dapp-kit v0.16.2 and it still fails. The problem is not on the kit, it's on the Slush web wallet which seems not to manage the ZKLogin epoch well. Could you reopen this issue and check it out? Thanks

**Comment by williamrobertson13** [comment]
So v0.1.2 of `@mysten/slush-wallet` has the [fix](https://github.com/MystenLabs/ts-sdks/pull/274), dApp-kit v0.16.2 has the updated dependency for `@mysten/slush-wallet`. It looks like you're signing the message for `testnet` but verifying against `mainnet`. Check out this section on the docs site: https://sdk.mystenlabs.com/typescript/cryptography/keypairs#verifying-zklogin-signatures.
