### ISSUE TITLE
sui-tool always fails

### ISSUE THREAD

**Issue by jaeik-kim** [MystenLabs/sui#24730]
## sui-tool version

sui-tool 1.62.1-1073a8fbf6cf

```shell
sui-tool download-formal-snapshot \
        --latest \
        --genesis "/etc/genesis.blob" \
        --network mainnet \
        --path /sui/snap \
        --num-parallel-downloads 6 \
        --no-sign-request
```

## Error Result

```
Generic HTTP error: Request error: Error after 0 retries in 105.114053917s, max_retries:0, retry_timeout:61s, source:error sending request for url (https://checkpoints.mainnet.sui.io/225703928.chk)

Caused by:
    0: Request error: Error after 0 retries in 105.114053917s, max_retries:0, retry_timeout:61s, source:error sending request for url (https://checkpoints.mainnet.sui.io/225703928.chk)
    1: Error after 0 retries in 105.114053917s, max_retries:0, retry_timeout:61s, source:error sending request for url (https://checkpoints.mainnet.sui.io/225703928.chk)
    2: error sending request for url (https://checkpoints.mainnet.sui.io/225703928.chk)
    3: operation timed out

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
   2: <S as futures_core::stream::TryStream>::try_poll_next
   3: <futures_util::stream::try_stream::try_for_each::TryForEach<St,Fut,F> as core::future::future::Future>::poll
   4: sui_tool::download_formal_snapshot::{{closure}}::{{closure}}
   5: tokio::runtime::task::harness::Harness<T,S>::poll
   6: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   7: tokio::runtime::scheduler::multi_thread::worker::Context::run
   8: tokio::runtime::context::scoped::Scoped<T>::set
   9: tokio::runtime::context::runtime::enter_runtime
  10: tokio::runtime::scheduler::multi_thread::worker::run
  11: tokio::runtime::task::core::Core<T,S>::poll
  12: tokio::runtime::task::harness::Harness<T,S>::poll
  13: tokio::runtime::blocking::pool::Inner::run
  14: std::sys::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: std::sys::pal::unix::thread::Thread::new::thread_start
  17: <unknown>
  18: clone
```

**Comment by stefan-mysten** [comment]
@johnjmartin any idea what might be wrong here?

@jaeik-kim is this now working or is it still throwing the same error?

**Comment by johnjmartin** [comment]
I've merged some recent fixes into main which should help with these types of failures

**Comment by phips28** [comment]
@johnjmartin  this still fails every time I run this. tried 5 times already with 5 parallel downloads, it always gets killed when accumulation completes. always on different checkpoints.

```
[00:27:42] ███████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 230537/393901 transactions backfilled (138.6 chkpts/sec)
[00:00:10] ███████████████████████████████████████████████████████████████████████████████████████████ 1194/1194 (Checkpoint summary sync is complete)
[00:08:52] ████████████████████████████████████████████████████████████ 1414 out of 1414 missing .ref files done (Missing ref files download complete)
[00:00:01] ███████████████████████████████████████████████████████████████████████████████████ 1194/1194 (Checkpoint summary verification is complete)
[00:00:23] ████████████████████████████████████████████████████████████████████████████ 1414 out of 1414 ref files checksummed (Checksumming complete)
[00:18:22] ██████████████████████████████████████████████████████████████ 1414 out of 1414 ref files accumulated from snapshot (Accumulation complete)
[00:00:00] ███████████████████████████████████████████████████████████████ Verifying snapshot contents against root state hash (Verification complete)Generic HTTP error: Error performing GET https://checkpoints.mainnet.sui.io/300459559.binpb.zst in 65.540911221s - HTTP error: error sending request

Caused by:
    0: Error performing GET https://checkpoints.mainnet.sui.io/300459559.binpb.zst in 65.540911221s - HTTP error: error sending request
    1: HTTP error: error sending request
    2: HTTP error: error sending request
    3: error sending request
    4: operation timed out
```
