### ISSUE TITLE
[Wallet-Kit] Bug when using Next.js 13, getServerSnapshot error

### ISSUE THREAD

**Issue by BladeRunner713** [MystenLabs/sui#9389]
When I use wallet-kit and next.js 13 together. The error occurs. Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.

**Comment by kamyardl** [comment]
1. First, make sure you have the latest version of the software installed. You can check this by typing "npm install -g sui" in your command line.

2. If you still encounter the same error, try clearing your cache by typing "npm cache clean".

3. If the problem persists, try uninstalling and reinstalling the software by typing "npm uninstall -g sui" followed by "npm install -g sui".

4. If none of these steps work, you may need to examine your source code to look for any potential errors in your code. Alternatively, you can reach out to the MystenLabs support team for further assistance.

I hope these steps help you resolve the issue you are facing. Good luck!

**Comment by bankheist** [comment]
Hey, I have this issue also. I've tried all the above steps and it doesn't seem to resolve the bug.

**Comment by Jordan-Mysten** [comment]
This has been resolved on main and will be released soon.

**Comment by WhiskeyRomeoTango** [comment]
Sorry to reopen this but is this already released? I see a recent release on npm very recently (0.3.3) but I still have this error. My `_app.jsx` was set up like this, And then `Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.`

```
export default function App({ Component, pageProps }) {
  return (
    <>
      <main>
        <div>
          <WalletKitProvider>
            <Component {...pageProps} />
          </WalletKitProvider>
        </div>
      </main>
    </>
  )
}
```

**Comment by Jordan-Mysten** [comment]
Hasn't been released yet, but it should be released soon!
